blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://github.com/auth0/auth0-vue/blob/master/FAQ.md
    about: Read the FAQ to get answers to common issues
  - name: SDK API Documentation
    url: https://auth0.github.io/auth0-vue/
    about: Read the API documentation for this SDK
